### ISSUE TITLE
考虑支持通过token获取吗，就像Snap.HuTao那样?

### ISSUE THREAD

**Issue by YaKun9** [cntvc/star-rail-tools#2]
### 你当前使用的软件版本 (The software version you are currently using)

没使用

### 描述一下背景以及具体的功能或优化点 (Describe the feature and reason)

考虑支持通过token获取吗，就像Snap.HuTao那样?

**Comment by cntvc** [comment]
目前已有的三种导出方式已经可以覆盖大部分电脑玩家的使用场景了，所以什么情况下需要用这个方式呢（~~懒得研究~~)

**Comment by YaKun9** [comment]
当然是为了~~摸鱼~~在其他电脑上看咯

**Comment by cntvc** [comment]
好吧，这个功能已经添加到计划表中了，预计两个版本内会上线

**Comment by YaKun9** [comment]
![082738DB](https://github.com/cntvc/star-rail-tools/assets/131952790/3ba25542-63bf-4bca-92aa-ed297867d0da)
期待

**Comment by cntvc** [comment]
经过调查，星铁并没有类似接口可以获得authkey，这个功能无法实现
